services:
    - docker

env:
    - BUILD_CFG=arch
    - BUILD_CFG=ubuntu
    - BUILD_CFG=ubuntu-multiuser
    - BUILD_CFG=debian

script:
    - |
        if [ "$BUILD_CFG" == "ubuntu-multiuser" ]; then
            travis_retry docker run \
                --rm \
                -v $PWD:/tmp/Dotfile-tools \
                ubuntu:rolling \
                bash -c "useradd -ms /bin/bash joe && \
                         usermod -aG sudo joe && \
                         apt update && \
                         apt -y install \
                             sudo \
                             make && \
                         echo 'joe ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
                         su joe -c 'cd /tmp/Dotfile-tools && \
                         sudo make ansible' && \
                         su joe -c 'cd /tmp/Dotfile-tools && \
                         sudo make test'"
        elif [ "$BUILD_CFG" == "ubuntu" ]; then
            travis_retry docker run \
                --rm \
                -v $PWD:/tmp/Dotfile-tools \
                ubuntu:rolling \
                bash -c "apt update && \
                         apt -y install \
                             sudo \
                             make && \
                         cd /tmp/Dotfile-tools && \
                         make ansible && \
                         make test"
        elif [ "$BUILD_CFG" == "debian" ]; then
            travis_retry docker run \
                --rm \
                -v $PWD:/tmp/Dotfile-tools \
                debian:latest \
                bash -c "apt update && \
                         apt -y install \
                             sudo \
                             make \
                             gnupg && \
                         cd /tmp/Dotfile-tools && \
                         make ansible && \
                         make test"
        elif [ "$BUILD_CFG" == "arch" ]; then
            travis_retry docker run \
                --rm \
                -v $PWD:/tmp/Dotfile-tools \
                cognexa/archlinux:latest \
                bash -c "sed -i 's/Required DatabaseOptional/Never/g' /etc/pacman.conf && \
                         yes Y | pacman --noconfirm -Syu && \
                         yes Y | pacman -S --noconfirm \
                             sudo \
                             which \
                             gawk \
                             python \
                             make && \
                         cd /tmp/Dotfile-tools && \
                         sudo -u aur bash -c 'cd /tmp/Dotfile-tools && sudo make ansible && sudo make test'"
        fi
