---

- name: Install dotfile dependencies using sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - fontconfig
    - git
    - tmux
    - wget
    - zsh
  become: yes
  become_method: sudo
  tags:
    - packages

- name: Install doom emacs
  include: doom-emacs.yml
  tags:
    - emacs

- name: Install tmux plugin manager
  include: tmux.yml
  tags:
    - tmux
