---

- name: Install dotfile dependencies using sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - fontconfig
    - git
    - wget
  become: yes
  become_method: sudo
