
---
- name: Window manager deployment
  hosts: localhost
  vars:
    gen_warning: "WARINING! This file is controlled by Ansible."
    local_home: "{{ lookup('env', 'HOME') }}"
    local_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Check if Font_Awesome is installed
      stat:
        path: /usr/share/fonts/opentype/FontAwesome5FreeSolid-900.otf
      register: stat_result_awesome
      become: yes
      become_user: root
      become_method: sudo
        
    - name: Create Font-Awesome folder
      file:
        state: directory
        path: /usr/share/fonts/opentype
        recurse: yes
      become: yes
      become_user: root
      become_method: sudo

    - name: Copy Font-Awesome folder
      copy:
        src: "{{ local_home }}/.homesick/repos/dotfiles/home/fonts/Font-Awesome/otfs/{{ item.src }}"
        dest: "/usr/share/fonts/opentype/{{ item.dst }}"
      with_items:
        - { src: "Font Awesome 5 Brands-Regular-400.otf", dst: "FontAwesome5BrandsRegular-400.otf" }
        - { src: "Font Awesome 5 Free-Regular-400.otf", dst: "FontAwesome5FreeRegular-400.otf" }
        - { src: "Font Awesome 5 Free-Solid-900.otf", dst: "FontAwesome5FreeSolid-900.otf" }
      when: stat_result_awesome.stat.exists == False
      become: yes
      become_user: root
      become_method: sudo
      
        
          
